### ISSUE TITLE
RDR 2 Vulkan more issues

### ISSUE THREAD

**Issue by JIStream** [bruhmoment21/UniversalHookX#10]
Can't reopen original issue. It renders the menu now but I can't interact with it in any way. Do I need to implement something on my side to make it work? We can move back to the original issue if you reopen it.

**Comment by JIStream** [comment]
I guess demo menu just has no functionality, I'm stupid, closing the issue.

**Comment by bruhmoment21** [comment]
> I guess demo menu just has no functionality, I'm stupid, closing the issue.
> 
> Edit: or maybe it was hooked too early, the point is, my custom menu works as expected, not sure what's the issue with demo was.

hmm usually when games do this (hides cursor or whatever) i open an menu or console and then use the menu (ghetto workaround)

**Comment by JIStream** [comment]
> > I guess demo menu just has no functionality, I'm stupid, closing the issue.
> > Edit: or maybe it was hooked too early, the point is, my custom menu works as expected, not sure what's the issue with demo was.
> 
> hmm usually when games do this (hides cursor or whatever) i'll open a menu or console and then use the menu (ghetto workaround)

Cursor was on the screen, hover effects were there but clicks just didn't come through.

**Comment by bruhmoment21** [comment]
i don't experience it but good for you if its working
