### ISSUE TITLE
Dynamic Vtable Index Recover

### ISSUE THREAD

**Issue by stevemk14ebr** [bruhmoment21/UniversalHookX#11]
Hey, your vtable hooks have hardcoded indices, you can recover these dynamically using this:

https://gist.github.com/stevemk14ebr/12d70ae90175e71194520e9bb0c5e1e5

Example of what I mean:
https://github.com/bruhmoment21/UniversalHookX/blob/1e5496720c0493a9b79360fb82f8cca512eff956/UniversalHookX/src/hooks/backend/dx12/hook_directx12.cpp#L214-L226

**Comment by bruhmoment21** [comment]
i don't think windows will ever change the indexes but this is a good addition

**Comment by stevemk14ebr** [comment]
I agree with you, you could use it to unify parts of the directx hooks across versions though.
