### ISSUE TITLE
DIRECTX9 Mouse clicks in game interface

### ISSUE THREAD

**Issue by bymcs** [bruhmoment21/UniversalHookX#2]
Hello mouse clicks in game interface not working properly ,
In-game mouse clicks working properly before injecting dll ,
this looks like an imgui issue, can you help if you know ?
if you watch the video you can understand what i mean

https://user-images.githubusercontent.com/56798318/179370454-42fe41d2-dce7-45b9-8d6b-2e591c292f48.mp4

game link : ` https://www.origins2.global `

 ### edit: I noticed that if I press right and left click at the same time it works like normal left click
 ### new information : clicking issue returns to normal when imgui window is hidden.

https://user-images.githubusercontent.com/56798318/179388211-e35bc90a-5890-46f7-b8f5-b25ce98046eb.mp4

**Comment by bymcs** [comment]
I think the click problem is caused by the "WndProc" function

**Comment by bymcs** [comment]
I've solved the problem, I'll share it when it's available

**Comment by bruhmoment21** [comment]
hey sorry for the late reply but i stated in the readme that input handling is left to you to decide it.
> Input handling is up to you to decide how to make/use it.

You could've tried to uncomment [this](https://github.com/bruhmoment21/UniversalHookX/blob/main/UniversalHookX/src/hooks/hooks.cpp#L67) line and comment [the one above it](https://github.com/bruhmoment21/UniversalHookX/blob/main/UniversalHookX/src/hooks/hooks.cpp#L62).

**Comment by bymcs** [comment]
@bruhmoment21 hello, I encountered another problem, I cannot use the dll file that I compiled from my own computer on another computer.

![VirtualBoxVM_SkIYUBnqc6](https://user-images.githubusercontent.com/56798318/180636663-4fc9151c-e1d8-4fd2-8c1d-7f7af84b5e21.png)

**Comment by bymcs** [comment]
solution: windows sdk must be installed
