### ISSUE TITLE
Doom Eternal - Black Screen (VULKAN)

### ISSUE THREAD

**Issue by DJD320** [bruhmoment21/UniversalHookX#3]
As already stated in the title, i am having problems with the game Doom Eternal which uses vulkan.
If i inject the dll, as soon as the game starts, i manage to see the ImGui menu, but after the first loading screen (when starts rendering actual game stuff), everything freezes then becomes black.

Even when injecting after that loading screen, the result is always a black screen.

VIDEO: https://streamable.com/c0wh0d

**Comment by bruhmoment21** [comment]
been looking at this i am still looking at the issue seems like the game does some stuff with multiple queues

**Comment by bruhmoment21** [comment]
the game uses async rendering, to disable that add +r_enableAsyncCompute 2 in your launch options (this is a workaround, not a fix) and you should see the imgui window. The freeze is the result of calling vkQueueSubmit on a compute queue. (queue family 2) lmk if it works

**Comment by DJD320** [comment]
Hi, i tried what you suggested and it indeed worked!
The only issue is the mouse capture, which is not working as the mouse gets ignored by the imgui window.

https://i.ibb.co/gD6fvYF/image.png

I think that this issue can be fixed with some code regarding imgui's io. something like `WantCaptureMouse` if i'm not wrong.

**Comment by bruhmoment21** [comment]
> Hi, i tried what you suggested and it indeed worked! The only issue is the mouse capture, which is not working as the mouse gets ignored by the imgui window.
> 
> https://i.ibb.co/gD6fvYF/image.png
> 
> I think that this issue can be fixed with some code regarding imgui's io. something like `WantCaptureMouse` if i'm not wrong.

hhmm i don t think it will work a workaround for that would be to open the games console by pressing "`" same button as csgo consoles.

**Comment by DJD320** [comment]
indeed it didnt work. i changed the toggle menu bind from vk_insert to the "`" key, that way its synced.
