### ISSUE TITLE
"Vulkan backend is not enabled!" on a game that uses vulkan-1.dll

### ISSUE THREAD

**Issue by User13445** [bruhmoment21/UniversalHookX#4]
Hello! For starters... thank you for making this!
I've been looking around for a very long time, for a Vulkan Dear ImGui hook. 

So, I'm having an issue. I am currently trying this with a game called 'No Man's Sky'.  On previous versions of the game they used OpenGL as  a backend, but later on they switched to the Vulkan backend.  

I tried the hook on an older version of the game using OpenGL as an enum & it worked.  However, when I tried on the modern version of the game using Vulkan... this is what I see: 
![2022-07-30 - 15 27 31 ~ GH Injector - x64](https://user-images.githubusercontent.com/110306746/181959230-46f37518-66fb-4948-ba7f-8667b994cffa.png)

I'd be extremely grateful if you found a way to resolve this!

Feel free to let me know if any more information could be provided.

Regards

**Comment by bruhmoment21** [comment]
hey this is my bad because i left this undocumented. make sure you have [Vulkan SDK](https://vulkan.lunarg.com/sdk/home#windows) installed and [uncomment this line](https://github.com/bruhmoment21/UniversalHookX/blob/main/UniversalHookX/src/backend.hpp#L10)

**Comment by User13445** [comment]
Thank you so much! What you suggested fixed the issue.

 Yeah, the game forces your cursor into focus. ReShade has a way of getting around this. I'm not sure if it's ImGui specific, or if this will require writing some code for it on my behalf.

**Comment by User13445** [comment]
A bit of an update. 

So, I fixed the issue of the game still receiving input while the menu overlay is opened with the WndProc function.
However, re-opening the Dear ImGui produces a freeze/crash.

To see if this whether or not this was an issue with the  changes I made... I had tested with the original source code & unfortunately it crashed. 

So, this doesn't crash if you are on the main menu. But it does if you try to re-open ImGui if you are loaded in-game.

**Comment by bruhmoment21** [comment]
> A bit of an update.
> 
> So, I fixed the issue of the game still receiving input while the menu overlay is opened with the WndProc function. However, re-opening the Dear ImGui produces a freeze/crash.
> 
> To see if this whether or not this was an issue with the changes I made... I had tested with the original source code & unfortunately it crashed.
> 
> So, this doesn't crash if you are on the main menu. But it does if you try to re-open ImGui if you are loaded in-game.

couldn t reproduce https://streamable.com/bukfcj

**Comment by User13445** [comment]
Re-installing the game through Steam has fixed this issue. Thanks again for your help & your time!
