### ISSUE TITLE
Red Dead Redemption 2 Vulkan

### ISSUE THREAD

**Issue by JIStream** [bruhmoment21/UniversalHookX#9]
It seems ImGUI menu is not showing in RDR 2 with Vulkan. Hooks fine but pressing insert doesn't bring up the menu. As far as I can tell, Async Compute is an option in RDR 2 and can be disabled in settings.xml which I did.

Unrelated but might help someone: if you are trying to use this hook with ScriptHookRDR2, you'll probably need to add some delay before hooking Vulkan since ScriptHook attaches your asi as soon as the game starts and that crashes (debug console just closes) UniversalHookX.

Console Log:
![image](https://user-images.githubusercontent.com/36078424/213762886-67269502-ef59-4bcf-9dee-70e7f5ebbef2.png)

**Comment by JIStream** [comment]
Also worth noting that I've added LOG() messages to both the function that calls Menu::Render() and Menu::Render() itself and those messages don't appear in the console at all.

**Comment by bruhmoment21** [comment]
let me know if the last commit fixed it

**Comment by JIStream** [comment]
Yes, it did. Thank you.

**Comment by JIStream** [comment]
Spoke too soon. It renders the menu now but I can't interact with it in any way. Do I need to implement something on my side to make it work?
